import { User, BusinessProfile, FreelancerProfile, FundingRequest, Job, JobApplication, Payment, Review, Withdrawal } from './types';

// Mock Users
export const mockUsers: User[] = [
  // Business Owners
  {
    id: 'user-1',
    name: 'Thabo Mokoena',
    email: 'thabo@techsolutions.co.za',
    role: 'business',
    verified: true,
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Nomsa Dlamini',
    email: 'nomsa@craftcorner.co.za',
    role: 'business',
    verified: true,
    createdAt: '2025-02-20T10:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Sipho Ndlovu',
    email: 'sipho@greenservices.co.za',
    role: 'business',
    verified: true,
    createdAt: '2025-03-05T10:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Zanele Khumalo',
    email: 'zanele@fashionhub.co.za',
    role: 'business',
    verified: true,
    createdAt: '2025-04-12T10:00:00Z',
  },
  // Freelancers
  {
    id: 'user-5',
    name: 'Lerato Khumalo',
    email: 'lerato@freelance.co.za',
    role: 'freelancer',
    verified: true,
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'user-6',
    name: 'Mandla Mthembu',
    email: 'mandla.dev@gmail.com',
    role: 'freelancer',
    verified: true,
    createdAt: '2025-03-10T10:00:00Z',
  },
  {
    id: 'user-7',
    name: 'Precious Ngwenya',
    email: 'precious.writes@gmail.com',
    role: 'freelancer',
    verified: true,
    createdAt: '2025-04-05T10:00:00Z',
  },
  {
    id: 'user-8',
    name: 'Thandi Sibeko',
    email: 'thandi.marketing@gmail.com',
    role: 'freelancer',
    verified: true,
    createdAt: '2025-05-01T10:00:00Z',
  },
  {
    id: 'user-9',
    name: 'Bongani Zulu',
    email: 'bongani.photo@gmail.com',
    role: 'freelancer',
    verified: true,
    createdAt: '2025-05-15T10:00:00Z',
  },
  // Municipal Workers
  {
    id: 'user-10',
    name: 'David van der Merwe',
    email: 'david@tshwane.gov.za',
    role: 'municipal',
    verified: true,
    createdAt: '2025-01-01T10:00:00Z',
  },
];

// Mock Business Profiles
export const mockBusinessProfiles: BusinessProfile[] = [
  {
    userId: 'user-1',
    companyName: 'Thabo\'s Tech Solutions',
    industry: 'Technology',
    description: 'Providing innovative tech solutions for local businesses including website development, IT support, and digital transformation services.',
    location: 'Pretoria Central, Tshwane',
    contactEmail: 'contact@thabotech.co.za',
    contactPhone: '+27 12 345 6789',
    documents: [],
  },
  {
    userId: 'user-2',
    companyName: 'Craft Corner',
    industry: 'Retail',
    description: 'Handmade crafts and artisanal products celebrating South African culture. We specialize in beadwork, pottery, and traditional textiles.',
    location: 'Hatfield, Tshwane',
    contactEmail: 'info@craftcorner.co.za',
    contactPhone: '+27 12 456 7890',
    documents: [],
  },
  {
    userId: 'user-3',
    companyName: 'Green Services Landscaping',
    industry: 'Services',
    description: 'Professional landscaping and garden maintenance services for residential and commercial properties across Tshwane.',
    location: 'Centurion, Tshwane',
    contactEmail: 'hello@greenservices.co.za',
    contactPhone: '+27 12 567 8901',
    documents: [],
  },
  {
    userId: 'user-4',
    companyName: 'Fashion Hub Boutique',
    industry: 'Retail',
    description: 'Contemporary African fashion boutique featuring local designers and sustainable clothing lines.',
    location: 'Brooklyn, Tshwane',
    contactEmail: 'style@fashionhub.co.za',
    contactPhone: '+27 12 678 9012',
    documents: [],
  },
];

// Mock Freelancer Profiles
export const mockFreelancerProfiles: FreelancerProfile[] = [
  {
    userId: 'user-5',
    bio: 'Experienced graphic designer and web developer with 5+ years in the industry. Specializing in brand identity, UI/UX design, and responsive web development.',
    skills: ['Graphic Design', 'Web Development', 'UI/UX Design', 'Branding', 'Adobe Creative Suite', 'Figma'],
    hourlyRate: 350,
    category: 'Design & Development',
    portfolio: 'https://lerato-designs.co.za/portfolio',
    rating: 4.8,
    reviewCount: 24,
    documents: [
      {
        id: 'doc-1',
        name: 'ID Document',
        type: 'id-document',
        url: 'https://example.com/documents/lerato-id.pdf',
        uploadedAt: '2025-02-15T10:00:00Z',
        verified: true,
      },
      {
        id: 'doc-2',
        name: 'Bachelor of Fine Arts Certificate',
        type: 'qualification',
        url: 'https://example.com/documents/lerato-degree.pdf',
        uploadedAt: '2025-03-01T10:00:00Z',
        verified: true,
      },
      {
        id: 'doc-3',
        name: 'Adobe Creative Suite Certification',
        type: 'certification',
        url: 'https://example.com/documents/lerato-adobe-cert.pdf',
        uploadedAt: '2025-03-15T10:00:00Z',
        verified: true,
      },
    ],
    idNumber: '8501011234567',
    qualifications: ['Bachelor of Fine Arts', 'Adobe Certified Expert'],
    certifications: ['Adobe Creative Suite Certification', 'Google UX Design Certificate'],
  },
  {
    userId: 'user-6',
    bio: 'Full-stack developer passionate about creating efficient, scalable web applications. Expert in React, Node.js, and cloud technologies.',
    skills: ['React', 'Node.js', 'JavaScript', 'TypeScript', 'AWS', 'MongoDB', 'PostgreSQL'],
    hourlyRate: 450,
    category: 'Software Development',
    portfolio: 'https://mandla-dev.co.za/portfolio',
    rating: 4.9,
    reviewCount: 18,
    documents: [],
    idNumber: '8602022345678',
    qualifications: ['Bachelor of Computer Science', 'AWS Certified Developer'],
    certifications: ['AWS Certified Solutions Architect', 'MongoDB Certified Developer'],
  },
  {
    userId: 'user-7',
    bio: 'Professional content writer and copywriter with expertise in SEO, blog posts, website copy, and marketing materials.',
    skills: ['Content Writing', 'Copywriting', 'SEO', 'Blog Writing', 'Social Media Content'],
    hourlyRate: 250,
    category: 'Writing & Content',
    portfolio: 'https://precious-writes.co.za/portfolio',
    rating: 4.7,
    reviewCount: 31,
    documents: [],
    idNumber: '8703033456789',
    qualifications: ['Bachelor of Journalism', 'SEO Specialist Certification'],
    certifications: ['Google Analytics Certified', 'Content Marketing Institute Certified'],
  },
  {
    userId: 'user-8',
    bio: 'Digital marketing specialist helping businesses grow their online presence through strategic social media marketing and email campaigns.',
    skills: ['Social Media Marketing', 'Email Marketing', 'Google Ads', 'Facebook Ads', 'Analytics'],
    hourlyRate: 300,
    category: 'Marketing',
    portfolio: 'https://thandi-marketing.co.za/portfolio',
    rating: 4.6,
    reviewCount: 15,
    documents: [],
    idNumber: '8804044567890',
    qualifications: ['Bachelor of Marketing', 'Digital Marketing Certification'],
    certifications: ['Facebook Blueprint Certified', 'Google Ads Certified'],
  },
  {
    userId: 'user-9',
    bio: 'Professional photographer specializing in product photography, events, and corporate headshots. Creating stunning visuals for businesses.',
    skills: ['Photography', 'Photo Editing', 'Product Photography', 'Event Photography', 'Adobe Lightroom'],
    hourlyRate: 400,
    category: 'Photography & Video',
    portfolio: 'https://bongani-photo.co.za/portfolio',
    rating: 4.9,
    reviewCount: 22,
    documents: [],
    idNumber: '8905055678901',
    qualifications: ['Bachelor of Fine Arts in Photography', 'Professional Photography Certification'],
    certifications: ['Adobe Certified Expert in Lightroom', 'Wedding and Portrait Photographers International Certified'],
  },
];

// Mock Funding Requests
export const mockFundingRequests: FundingRequest[] = [
  {
    id: 'fund-1',
    businessId: 'user-1',
    businessName: 'Thabo\'s Tech Solutions',
    amount: 50000,
    purpose: 'Equipment Purchase',
    description: 'Need funding to purchase new computers, software licenses, and IT equipment for office expansion. This will allow us to serve 5 additional clients simultaneously.',
    status: 'pending',
    createdAt: '2025-10-10T10:00:00Z',
    updatedAt: '2025-10-10T10:00:00Z',
    industry: 'Technology',
  },
  {
    id: 'fund-2',
    businessId: 'user-1',
    businessName: 'Thabo\'s Tech Solutions',
    amount: 25000,
    purpose: 'Marketing Campaign',
    description: 'Launch digital marketing campaign to reach more customers in the Tshwane area through Google Ads and social media advertising.',
    status: 'funded',
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-09-22T10:00:00Z',
    industry: 'Technology',
  },
  {
    id: 'fund-3',
    businessId: 'user-2',
    businessName: 'Craft Corner',
    amount: 35000,
    purpose: 'Inventory Expansion',
    description: 'Purchase raw materials and supplies to expand our product line. Will create employment for 3 additional local artisans.',
    status: 'approved',
    createdAt: '2025-10-05T10:00:00Z',
    updatedAt: '2025-10-12T10:00:00Z',
    industry: 'Retail',
  },
  {
    id: 'fund-4',
    businessId: 'user-2',
    businessName: 'Craft Corner',
    amount: 15000,
    purpose: 'E-commerce Website',
    description: 'Develop an e-commerce platform to sell our products online and reach customers beyond Tshwane.',
    status: 'pending',
    createdAt: '2025-10-14T10:00:00Z',
    updatedAt: '2025-10-14T10:00:00Z',
    industry: 'Retail',
  },
  {
    id: 'fund-5',
    businessId: 'user-3',
    businessName: 'Green Services Landscaping',
    amount: 45000,
    purpose: 'Equipment & Vehicle',
    description: 'Purchase commercial lawn mowers, trimmers, and a delivery vehicle to expand our service capacity.',
    status: 'funded',
    createdAt: '2025-08-20T10:00:00Z',
    updatedAt: '2025-09-01T10:00:00Z',
    industry: 'Services',
  },
  {
    id: 'fund-6',
    businessId: 'user-3',
    businessName: 'Green Services Landscaping',
    amount: 20000,
    purpose: 'Staff Training',
    description: 'Professional training and certification for 5 staff members in advanced landscaping techniques and safety protocols.',
    status: 'rejected',
    createdAt: '2025-07-10T10:00:00Z',
    updatedAt: '2025-07-18T10:00:00Z',
    industry: 'Services',
  },
  {
    id: 'fund-7',
    businessId: 'user-4',
    businessName: 'Fashion Hub Boutique',
    amount: 30000,
    purpose: 'Store Renovation',
    description: 'Renovate store interior, install new displays, and improve lighting to enhance customer shopping experience.',
    status: 'approved',
    createdAt: '2025-10-08T10:00:00Z',
    updatedAt: '2025-10-13T10:00:00Z',
    industry: 'Retail',
  },
  {
    id: 'fund-8',
    businessId: 'user-4',
    businessName: 'Fashion Hub Boutique',
    amount: 18000,
    purpose: 'Inventory Purchase',
    description: 'Stock new fashion collection from local South African designers for the upcoming summer season.',
    status: 'pending',
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2025-10-15T10:00:00Z',
    industry: 'Retail',
  },
];

// Mock Jobs
export const mockJobs: Job[] = [
  {
    id: 'job-1',
    businessId: 'user-1',
    businessName: 'Thabo\'s Tech Solutions',
    title: 'Logo Design for Tech Startup',
    description: 'We need a modern, professional logo for our tech company. Should include both text and icon versions, with variations for light and dark backgrounds. Final deliverables in vector format.',
    budget: 3500,
    requiredSkills: ['Graphic Design', 'Adobe Illustrator', 'Branding', 'Logo Design'],
    duration: '2 weeks',
    deadline: '2025-11-01',
    location: 'Pretoria Central, Tshwane',
    status: 'open',
    createdAt: '2025-10-12T10:00:00Z',
  },
  {
    id: 'job-2',
    businessId: 'user-1',
    businessName: 'Thabo\'s Tech Solutions',
    title: 'Company Website Development',
    description: 'Build a responsive company website with portfolio section, service pages, and contact forms. Must be SEO-friendly and mobile-optimized.',
    budget: 15000,
    requiredSkills: ['Web Development', 'React', 'CSS', 'JavaScript', 'SEO'],
    duration: '1 month',
    deadline: '2025-11-15',
    location: 'Pretoria Central, Tshwane',
    status: 'open',
    createdAt: '2025-10-14T10:00:00Z',
  },
  {
    id: 'job-3',
    businessId: 'user-2',
    businessName: 'Craft Corner',
    title: 'Product Photography - 50 Items',
    description: 'Professional photography needed for our handmade craft products. Clean, well-lit photos for our e-commerce website and social media.',
    budget: 5000,
    requiredSkills: ['Photography', 'Product Photography', 'Photo Editing', 'Adobe Lightroom'],
    duration: '1 week',
    deadline: '2025-10-28',
    location: 'Hatfield, Tshwane',
    status: 'open',
    createdAt: '2025-10-13T10:00:00Z',
  },
  {
    id: 'job-4',
    businessId: 'user-2',
    businessName: 'Craft Corner',
    title: 'Social Media Content Creation',
    description: 'Create engaging social media content for Instagram and Facebook. 20 posts per month with captions and hashtags focused on African crafts and culture.',
    budget: 4000,
    requiredSkills: ['Social Media Marketing', 'Content Writing', 'Graphic Design', 'Instagram'],
    duration: '1 month',
    deadline: '2025-11-30',
    location: 'Hatfield, Tshwane',
    status: 'open',
    createdAt: '2025-10-10T10:00:00Z',
  },
  {
    id: 'job-5',
    businessId: 'user-3',
    businessName: 'Green Services Landscaping',
    title: 'SEO & Blog Content Writer',
    description: 'Write 10 SEO-optimized blog posts about landscaping, gardening tips, and plant care for South African climate. 800-1000 words each.',
    budget: 3000,
    requiredSkills: ['Content Writing', 'SEO', 'Blog Writing', 'Research'],
    duration: '2 weeks',
    deadline: '2025-11-05',
    location: 'Centurion, Tshwane',
    status: 'open',
    createdAt: '2025-10-11T10:00:00Z',
  },
  {
    id: 'job-6',
    businessId: 'user-4',
    businessName: 'Fashion Hub Boutique',
    title: 'Fashion Lookbook Design',
    description: 'Design a 20-page digital fashion lookbook showcasing our new collection. Must have modern, elegant layout suitable for both web and print.',
    budget: 6000,
    requiredSkills: ['Graphic Design', 'Adobe InDesign', 'Photography', 'Layout Design'],
    duration: '3 weeks',
    deadline: '2025-11-20',
    location: 'Brooklyn, Tshwane',
    status: 'open',
    createdAt: '2025-10-09T10:00:00Z',
  },
  {
    id: 'job-7',
    businessId: 'user-4',
    businessName: 'Fashion Hub Boutique',
    title: 'Email Marketing Campaign',
    description: 'Design and implement email marketing campaign to promote new collection. Includes newsletter design, copywriting, and campaign setup.',
    budget: 2500,
    requiredSkills: ['Email Marketing', 'Copywriting', 'Graphic Design', 'Marketing'],
    duration: '1 week',
    deadline: '2025-10-30',
    location: 'Brooklyn, Tshwane',
    status: 'closed',
    createdAt: '2025-09-20T10:00:00Z',
  },
];

// Mock Job Applications
export const mockJobApplications: JobApplication[] = [
  {
    id: 'app-1',
    jobId: 'job-1',
    freelancerId: 'user-5',
    freelancerName: 'Lerato Khumalo',
    coverLetter: 'I have extensive experience in logo design and branding, with over 5 years creating memorable brand identities for tech companies. I would love to help bring your vision to life! My portfolio includes work for similar startups in the Pretoria area.',
    proposedRate: 3500,
    status: 'pending',
    createdAt: '2025-10-13T10:00:00Z',
  },
  {
    id: 'app-2',
    jobId: 'job-2',
    freelancerId: 'user-6',
    freelancerName: 'Mandla Mthembu',
    coverLetter: 'As a full-stack developer specializing in React, I can build a modern, responsive website that perfectly showcases your services. I\'ve completed similar projects for tech companies and understand the importance of SEO and mobile optimization.',
    proposedRate: 15000,
    status: 'accepted',
    createdAt: '2025-10-14T10:00:00Z',
  },
  {
    id: 'app-3',
    jobId: 'job-2',
    freelancerId: 'user-5',
    freelancerName: 'Lerato Khumalo',
    coverLetter: 'I offer both design and development services. I can create a beautiful, functional website with great UI/UX and ensure it\'s optimized for search engines.',
    proposedRate: 16000,
    status: 'rejected',
    createdAt: '2025-10-14T10:00:00Z',
  },
  {
    id: 'app-4',
    jobId: 'job-3',
    freelancerId: 'user-9',
    freelancerName: 'Bongani Zulu',
    coverLetter: 'Professional product photography is my specialty! I have experience shooting handmade items and crafts. I use professional lighting and editing to make products stand out. Can deliver high-res images perfect for e-commerce.',
    proposedRate: 5000,
    status: 'accepted',
    createdAt: '2025-10-13T10:00:00Z',
  },
  {
    id: 'app-5',
    jobId: 'job-4',
    freelancerId: 'user-8',
    freelancerName: 'Thandi Sibeko',
    coverLetter: 'Social media marketing is what I do best! I understand how to create engaging content that resonates with audiences interested in African crafts and culture. I\'ll help you build a strong online presence and connect with your target market.',
    proposedRate: 4000,
    status: 'pending',
    createdAt: '2025-10-11T10:00:00Z',
  },
  {
    id: 'app-6',
    jobId: 'job-4',
    freelancerId: 'user-7',
    freelancerName: 'Precious Ngwenya',
    coverLetter: 'I can create compelling captions and posts that tell your brand story. With experience in cultural content and hashtag research, I\'ll help you reach the right audience.',
    proposedRate: 3500,
    status: 'pending',
    createdAt: '2025-10-10T10:00:00Z',
  },
  {
    id: 'app-7',
    jobId: 'job-5',
    freelancerId: 'user-7',
    freelancerName: 'Precious Ngwenya',
    coverLetter: 'As an SEO content writer, I can create engaging, informative blog posts that will drive traffic to your website. I\'ll research topics relevant to your South African audience and optimize each post for search engines.',
    proposedRate: 3000,
    status: 'accepted',
    createdAt: '2025-10-11T10:00:00Z',
  },
  {
    id: 'app-8',
    jobId: 'job-6',
    freelancerId: 'user-5',
    freelancerName: 'Lerato Khumalo',
    coverLetter: 'I specialize in fashion lookbook design and have worked with several boutiques in Pretoria. I can create a stunning digital lookbook that showcases your collection beautifully across all platforms.',
    proposedRate: 6000,
    status: 'pending',
    createdAt: '2025-10-10T10:00:00Z',
  },
  {
    id: 'app-9',
    jobId: 'job-7',
    freelancerId: 'user-8',
    freelancerName: 'Thandi Sibeko',
    coverLetter: 'Email marketing is one of my core services. I can design beautiful newsletters, write compelling copy, and set up automated campaigns to promote your new collection effectively.',
    proposedRate: 2500,
    status: 'accepted',
    createdAt: '2025-09-21T10:00:00Z',
  },
];

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: 'pay-1',
    fromUserId: 'user-10',
    toUserId: 'user-1',
    amount: 25000,
    type: 'funding',
    status: 'completed',
    transactionId: 'TXN1728123456789ABC',
    createdAt: '2025-09-22T10:00:00Z',
    description: 'Funding payment for Marketing Campaign',
  },
  {
    id: 'pay-2',
    fromUserId: 'user-10',
    toUserId: 'user-3',
    amount: 45000,
    type: 'funding',
    status: 'completed',
    transactionId: 'TXN1728223456789DEF',
    createdAt: '2025-09-01T10:00:00Z',
    description: 'Funding payment for Equipment & Vehicle',
  },
  {
    id: 'pay-3',
    fromUserId: 'user-1',
    toUserId: 'user-6',
    amount: 15000,
    type: 'job-payment',
    status: 'completed',
    transactionId: 'TXN1728323456789GHI',
    createdAt: '2025-10-15T14:30:00Z',
    description: 'Payment to Mandla Mthembu for website development',
  },
  {
    id: 'pay-4',
    fromUserId: 'user-2',
    toUserId: 'user-9',
    amount: 5000,
    type: 'job-payment',
    status: 'completed',
    transactionId: 'TXN1728423456789JKL',
    createdAt: '2025-10-14T11:00:00Z',
    description: 'Payment to Bongani Zulu for product photography',
  },
  {
    id: 'pay-5',
    fromUserId: 'user-3',
    toUserId: 'user-7',
    amount: 3000,
    type: 'job-payment',
    status: 'completed',
    transactionId: 'TXN1728523456789MNO',
    createdAt: '2025-10-12T09:15:00Z',
    description: 'Payment to Precious Ngwenya for blog content',
  },
  {
    id: 'pay-6',
    fromUserId: 'user-4',
    toUserId: 'user-8',
    amount: 2500,
    type: 'job-payment',
    status: 'completed',
    transactionId: 'TXN1728623456789PQR',
    createdAt: '2025-09-28T16:45:00Z',
    description: 'Payment to Thandi Sibeko for email marketing campaign',
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 'rev-1',
    freelancerId: 'user-5',
    businessId: 'user-1',
    businessName: 'Thabo\'s Tech Solutions',
    rating: 5,
    comment: 'Excellent work! Lerato delivered beyond expectations. The designs were creative and professional.',
    createdAt: '2025-09-05T10:00:00Z',
  },
  {
    id: 'rev-2',
    freelancerId: 'user-6',
    businessId: 'user-1',
    businessName: 'Thabo\'s Tech Solutions',
    rating: 5,
    comment: 'Outstanding developer! Mandla built exactly what we needed and delivered on time. Highly recommended!',
    createdAt: '2025-10-16T10:00:00Z',
  },
  {
    id: 'rev-3',
    freelancerId: 'user-9',
    businessId: 'user-2',
    businessName: 'Craft Corner',
    rating: 5,
    comment: 'Bongani\'s product photos are absolutely stunning! Our products have never looked better. Great attention to detail.',
    createdAt: '2025-10-15T10:00:00Z',
  },
  {
    id: 'rev-4',
    freelancerId: 'user-7',
    businessId: 'user-3',
    businessName: 'Green Services Landscaping',
    rating: 4,
    comment: 'Good quality content. Precious wrote informative blog posts that are helping with our SEO. Minor revisions needed but overall very satisfied.',
    createdAt: '2025-10-13T10:00:00Z',
  },
  {
    id: 'rev-5',
    freelancerId: 'user-8',
    businessId: 'user-4',
    businessName: 'Fashion Hub Boutique',
    rating: 5,
    comment: 'Thandi created an amazing email campaign that drove real results! Our sales increased by 30%. Will definitely hire again.',
    createdAt: '2025-09-30T10:00:00Z',
  },
];

// Mock Withdrawals
export const mockWithdrawals: Withdrawal[] = [
  {
    id: 'with-1',
    freelancerId: 'user-6',
    amount: 10000,
    momoNumber: '27825551234',
    status: 'completed',
    transactionId: 'WTH1728723456789STU',
    createdAt: '2025-10-16T10:00:00Z',
  },
  {
    id: 'with-2',
    freelancerId: 'user-9',
    amount: 4000,
    momoNumber: '27825559876',
    status: 'completed',
    transactionId: 'WTH1728823456789VWX',
    createdAt: '2025-10-15T10:00:00Z',
  },
  {
    id: 'with-3',
    freelancerId: 'user-7',
    amount: 2500,
    momoNumber: '27825554321',
    status: 'completed',
    transactionId: 'WTH1728923456789YZA',
    createdAt: '2025-10-13T10:00:00Z',
  },
  {
    id: 'with-4',
    freelancerId: 'user-8',
    amount: 2000,
    momoNumber: '27825556543',
    status: 'completed',
    transactionId: 'WTH1729023456789BCD',
    createdAt: '2025-10-01T10:00:00Z',
  },
];
